name: se_verification

on:
  push:
    branches:
      - release
      - main

jobs:
  test:
    runs-on: code-default

    steps:
      - name: â¬‡ï¸ Checkout
        uses: code-actions/checkout@v2

      - name: âš¡ï¸ Set environment (Java)
        uses: code-actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          java-package: jdk
          cache: 'gradle'

      - name: ğŸ¸ Execute TCA checker
        run: java -jar .ahub/tcchecker-tca/tca-standalone-1.1.7.jar --outdir=./output --config=.ahub/tcchecker-tca/config.yaml --local=./ --logfile=./output/tcm.log

      - name: ğŸ‹ Upload TCM report
        uses: code-actions/upload-artifact@v3
        with:
          name: TCM Report
          path: ./output/

      - name: ğŸ¸ Execute Jacoco
        run: |
          chmod +x gradlew
          ./gradlew test jacocoRootReport

      - name: ğŸ‹ Upload Test Report
        uses: code-actions/upload-artifact@v3
        with:
          name: Test Report
          path: '**/**/build/test-results/test'

      - name: ğŸ‹ Upload Coverage Report
        uses: code-actions/upload-artifact@v3
        with:
          name: xmlcov
          path: ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

  ## Send reports to TestHub
  testhub:
    runs-on: code-default

    needs: test

    steps:
      - name: ğŸ‹ Send to TestHub
        uses: Code-Actions/testhub@v1
        with:
          test-tool: junit
          test-artifact-name: test_results
          coverage-tool: jacoco
          coverage-artifact-name: xmlcov
          plm-prj-code: RAJ0122ZZ-12RF
          release-key: SRRELEASE-1137
